// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpgioqucgmwfnekfitqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZ2lvcXVjZ213Zm5la2ZpdHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ5NjYxNTMsImV4cCI6MjA5MDU0MjE1M30.DqD1-brOW3XNmudHyppEVeil141qaH4w1a3v2TKAEBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});